package com.app.quickbite.auth.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * USER ENTITY - The Central "Hub" for Authentication
 * 
 * This is the main table that stores login credentials for ALL users in the system.
 * Every user (customer, restaurant owner, delivery agent, admin) has exactly one entry here.
 * 
 * Role-specific data lives in separate "spoke" tables (Restaurant, DeliveryAgent, etc.)
 * that reference this User table via foreign keys.
 */
@Entity
@Table(name = "users") // "user" is a reserved keyword in H2, so we use "users"
@Data // Lombok: generates getters, setters, toString, equals, hashCode
@NoArgsConstructor // Lombok: generates no-args constructor (required by JPA)
@AllArgsConstructor // Lombok: generates all-args constructor
public class User {
    
    /**
     * Primary key - auto-generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * User's full name (e.g., "John Doe")
     */
    @Column(nullable = false)
    private String fullName;
    
    /**
     * Email address - used as username for login
     * Must be unique across all users
     */
    @Column(nullable = false, unique = true)
    private String email;
    
    /**
     * Hashed password (never store plain text!)
     * This will be BCrypt-encoded by our service layer before saving
     */
    @Column(nullable = false)
    private String password;
    
    /**
     * Phone number for contact
     */
    @Column(nullable = false)
    private String phoneNumber;

    @Column(name = "default_delivery_address")
    private String defaultDeliveryAddress;
    
    /**
     * User's role in the system
     * Options: CUSTOMER, RESTAURANT_OWNER, DELIVERY_AGENT, ADMIN
     * 
     * We're using String for simplicity, but you could also use an Enum type
     */
    @Column(nullable = false)
    private String role;


    @Column(name = "email_verified")
    private Boolean emailVerified = false;  // Default to false


    /**
     * OAuth2 Provider used for authentication
     * NONE = traditional email/password auth
     * GOOGLE = Google OAuth2 authentication
     */
    @Column(name = "oauth_provider", nullable = true)
    @Enumerated(EnumType.STRING)  // Store as "NONE", "GOOGLE", etc. in database
    private AuthProvider oauthProvider;

    /**
     * OAuth2 Provider's Subject ID (unique identifier from provider)
     * For Google: this is the "sub" claim from the ID token
     */
    @Column(name = "oauth_id", nullable = true)
    private String oauthId;
}
